### ISSUE TITLE
Requesting changes to compilation

### ISSUE THREAD

**Issue by MakoStrwlkr** [CSC207-UofT/course-project-uwutever#17]
List of miscellaneous suggested changes for the compilation procedure(s):

1. FSAStateTransition class has lot of unnecessary methods;
2. Need to reach consensus on fate of the FSAState class;
3. Fix the NFA to DFA converter algorithm (not passing tests);
4. Refactor all NFA sub-classes, reduce code smell;
5. Add more unit tests for each component.

**Comment by bbrianh** [comment]
I could handle 3.

**Comment by bbrianh** [comment]
[NFA_design.pdf](https://github.com/CSC207-UofT/course-project-uwutever/files/7600037/NFA_design.pdf)

As shown in the above file, we could improve the implementation of NFA in two possible ways.

**Comment by bbrianh** [comment]
Perhaps we could have different implementations for NFA and DFA. We could use the graph implementation in NFA so we could take the advantage of the convenient manipulation of different states. Since the DFA doesn't require many node manipulations, DFA could be implemented in the quintuple representation where we use unique strings to represent every state.

**Comment by MakoStrwlkr** [comment]
All goals resolved except 5., for which unit tests need to be added for compilers, controllers, searcher. Franklin and I are working on it.
